[env:esp32-c3-devkitm-1]
platform = espressif32@6.10.0
board = adafruit_qtpy_esp32c3
framework = arduino

monitor_speed = 115200
upload_speed = 115200

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

monitor_filters =
    esp32_exception_decoder

board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson
    https://github.com/mandulaj/PZEM-004T-v30.git